message:
  queue:
    host: 127.0.0.1
server:
  port: 8080
spring:
  activemq:
    broker-url: tcp://${message.queue.host}:61616
    password: admin
    user: admin
  rabbitmq:
    host: ${message.queue.host}
    port: 3456
    username: admin
    password: 123456
rocketmq:
  name-server: ${message.queue.host}:9876
  producer:
    group: heyu-producer
    sendMessageTimeout: 300000
kafka:
  bootstrap-server: ${message.queue.host}:9092
heyu:
  rocketmq:
    topic:
      message: heyuomesssage
      object: heyuobject
      string: heyustring